name: Build en los Pull Requests
on:
  pull_request:
    branches:
      - main
      - features 

jobs: 
    build: 
      runs-on:
        ubuntu-latest  
      steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Setup Node.js
          uses: actions/setup-node@v4
          with:
            node-version: 20
        - name: Install dependencias
          run: npm ci

        - name: Build app
          run: npm run build
        
          
        
