name: Contenedor de Docker e imagen
on: 
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      # 1. Clonar el repo
      - uses: actions/checkout@v4

      # 2. Loguearse en GitHub Container Registry
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # 3. Configurar Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # 4. Generar variable de entorno para el usuario en minúsculas
      - name: Set lowercase repo owner
        run: echo "REPO_OWNER_LOWER=justingarciah" >> $GITHUB_ENV

      # 5. Build y push de la imagen Docker
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ghcr.io/justingarciah/plataforma-libro:latest
            ghcr.io/justingarciah/plataforma-libro:${{ github.sha }}
          build-args: |
            NODE_ENV=production
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new
